name: Validate Pull Request Reviews
description: Validate Pull Request Reviews
author: Shunsuke Suzuki
branding:
  icon: shield
  color: purple
inputs:
  # Optional
  trusted_apps:
    description: |
      Logins of Trusted apps.
      Each line must not end with "[bot]", and must not contain "/".
    required: false
    default: |
      renovate
      dependabot
  trusted_machine_users:
    description: |
      Logins of Trusted machine users.
      If a user matches with both `trusted_machine_users` and `untrusted_machine_users`, it is considered trusted.
      trusted_machine_users is useful to exclude specific machine users from regular expressions of untrusted_machine_users.
      e.g. Users with the suffix "-bot" are untrusted, but "suzuki-shunsuke-bot" is trusted.
      trusted_machine_users: |
        suzuki-shunsuke-bot
      untrusted_machine_users: |
        /-bot$/
    required: false
  untrusted_machine_users:
    description: |
      Logins of untrusted Machine Users.
      regular expressions are also available.
      Enclose a regular expression between slashes like `/-bot$/`.
      e.g.
      untrusted_machine_users: |
        mini-core
        /-bot$/
    required: false
  github_token:
    description: |
      GitHub Access Token.
      The permission `pull_requests:read` and `contents:read` are required.
    required: false
    default: ${{ github.token }}
  repository_owner:
    description: |
      The repository name of the pull request.
      The default value is `$GITHUB_REPOSITORY_OWNER`.
    required: false
    default: ${{ github.repository_owner }}
  repository_name:
    description: |
      The repository name of the pull request.
      The default value is the repository name of `$GITHUB_REPOSITORY`.
    required: false
    default: ${{ github.event.repository.name }}
  pull_request_number:
    description: |
      The pull request number.
    required: false
    default: ${{ github.event.pull_request.number }}
  # post_comment:
  #   description: |
  #     Whether to post a comment on the pull request.
  #   required: false
  #   default: "false"
runs:
  using: "node20"
  main: "dist/index.js"
