name: Validate PR Reviews
description: Validate PR Reviews
author: Shunsuke Suzuki
branding:
  icon: lock
  color: green
inputs:
  # Optional
  trusted_apps:
    description: |
      Trusted apps.
    required: false
    default: |
      renovate[bot]
      dependabot[bot]
  untrusted_machine_users:
    description: |
      Untrusted Machine Users.
    required: false
  github_token:
    description: |
      GitHub Access Token.
      The permission `pull_requests:read` and `contents:read` are required.
    required: false
    default: ${{ github.token }}
  repository_owner:
    description: |
      The repository name of the pull request.
      The default value is `$GITHUB_REPOSITORY_OWNER`.
    required: false
    default: ${{ github.repository_owner }}
  repository_name:
    description: |
      The repository name of the pull request.
      The default value is the repository name of `$GITHUB_REPOSITORY`.
    required: false
    default: ${{ github.event.repository.name }}
  pull_request_number:
    description: |
      The pull request number.
    required: false
    default: ${{ github.event.number }}
  # post_comment:
  #   description: |
  #     Whehter to post a comment on the pull request.
  #   required: false
  #   default: "false"
runs:
  using: "node20"
  main: "dist/index.js"
